#!/usr/bin/env python3
"""Generate the rule-pack reference page from the rules themselves.

    python scripts/gen_rule_docs.py --out docs/rule-pack.md

Keeping this generated means the documented pack can never drift from the
shipped pack.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tadori.core import attack  # noqa: E402
from tadori.core.fixtures import load_fixtures  # noqa: E402
from tadori.core.rules import Rule, load_rules  # noqa: E402

TACTIC_ORDER = [
    "initial-access",
    "execution",
    "persistence",
    "privilege-escalation",
    "defense-evasion",
    "credential-access",
    "discovery",
    "lateral-movement",
    "collection",
    "command-and-control",
    "exfiltration",
    "impact",
]


def tactics_of(rule: Rule) -> list[str]:
    found: list[str] = []
    for technique in rule.attack:
        for tactic in attack.tactics_of(technique):
            if tactic not in found:
                found.append(tactic)
    return found or ["uncategorised"]


def render(rules: list[Rule], fixture_counts: dict[str, int]) -> str:
    by_tactic: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        by_tactic[tactics_of(rule)[0]].append(rule)

    severities = defaultdict(int)
    for rule in rules:
        severities[rule.severity.value] += 1

    lines = [
        "# Rule pack",
        "",
        "<!-- generated by scripts/gen_rule_docs.py — do not edit by hand -->",
        "",
        f"{len(rules)} rules · "
        + " · ".join(f"{n} {s}" for s, n in sorted(severities.items()))
        + f" · {sum(fixture_counts.values())} fixtures",
        "",
        "Grouped by the ATT&CK for Mobile tactic of each rule's first technique.",
        "Writing your own: [rule reference](rules.md).",
        "",
    ]

    ordered = [t for t in TACTIC_ORDER if t in by_tactic]
    ordered += sorted(t for t in by_tactic if t not in TACTIC_ORDER)

    for tactic in ordered:
        lines += [f"## {tactic.replace('-', ' ').title()}", ""]
        lines += [
            "| rule | severity | scope | ATT&CK | fixtures |",
            "|---|---|---|---|---:|",
        ]
        for rule in sorted(by_tactic[tactic], key=lambda r: r.id):
            techniques = ", ".join(
                f"[{t}](https://attack.mitre.org/techniques/{t.replace('.', '/')}/)"
                for t in rule.attack
            )
            lines.append(
                f"| **`{rule.id}`** {rule.name} | {rule.severity.value} | {rule.scope} | "
                f"{techniques} | {fixture_counts.get(rule.id, 0)} |"
            )
        lines.append("")
        for rule in sorted(by_tactic[tactic], key=lambda r: r.id):
            if rule.description:
                lines.append(f"- **{rule.id}** — {rule.description.strip()}")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, help="write here instead of stdout")
    args = parser.parse_args()

    rules = load_rules()
    counts: dict[str, int] = defaultdict(int)
    for fixture in load_fixtures():
        counts[fixture.rule_id] += 1

    page = render(rules, counts)
    if args.out:
        args.out.write_text(page)
        print(f"wrote {args.out} ({len(rules)} rules)", file=sys.stderr)
    else:
        print(page)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
